### ISSUE TITLE
HEAD not working in Nexus

### ISSUE THREAD

**Issue by mwiktorczyk** [merll/docker-registry-util#3]
Is there any chance to choose on the command line between using HEAD or GET when reading manifest?
I see that the `client.py` already have `get_manifest` and I have tested that the tool is working properly with Nexus if replace each `head_manifest` to `get_manifest`.

**Comment by merll** [comment]
Yes, that should be possible to change. Using ``HEAD`` is just an addition in the [Docker Registry API](https://docs.docker.com/registry/spec/api/#manifest) to obtain the content digest without the other information. I will add this as an option.

**Comment by merll** [comment]
Fixed in release 1.0.3.
